In [54]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [55]:
data = pd.read_csv("/content/heart.csv")

In [56]:
data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

In [71]:
data.tail()

      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  target
1020   59    1   1       140   221  ...      0.0      2   0     2       1
1021   60    1   0       125   258  ...      2.8      1   1     3       0
1022   47    1   0       110   275  ...      1.0      1   1     2       0
1023   50    0   0       110   254  ...      0.0      2   0     2       1
1024   54    1   0       120   188  ...      1.4      1   1     3       0

[5 rows x 14 columns]

In [57]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [58]:
x=data.drop(columns='target', axis=1)
y=data['target']

In [59]:
print(x,y)

      age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0      52    1   0       125   212  ...      0      1.0      2   2     3
1      53    1   0       140   203  ...      1      3.1      0   0     3
2      70    1   0       145   174  ...      1      2.6      0   0     3
3      61    1   0       148   203  ...      0      0.0      2   1     3
4      62    0   0       138   294  ...      0      1.9      1   3     2
...   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
1020   59    1   1       140   221  ...      1      0.0      2   0     2
1021   60    1   0       125   258  ...      1      2.8      1   1     3
1022   47    1   0       110   275  ...      1      1.0      1   1     2
1023   50    0   0       110   254  ...      0      0.0      2   0     2
1024   54    1   0       120   188  ...      0      1.4      1   1     3

[1025 rows x 13 columns] 0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [60]:
scaler = StandardScaler()
x_scale = scaler.fit_transform(x)

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2 ,stratify=y,random_state=4)

In [62]:
model = LogisticRegression(solver='liblinear')
model.fit(x_train,y_train)
x_predict = model.predict(x_train)
accuracy = accuracy_score(x_predict,y_train)
print(accuracy)
#

0.8597560975609756

In [63]:
y_predict = model.predict(x_test)
accuracy = accuracy_score(y_predict,y_test)
print(accuracy)

0.8341463414634146

predictive system

In [70]:
input_data = (34,0,1,118,210,0,1,192,0,0.7,2,0,2)
n_array = np.asarray(input_data)
n_reshape = n_array.reshape(1,-1)
std_data = scaler.transform(n_reshape)
prediction = model.predict(std_data)
print(prediction)
if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[1]
The Person has Heart Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(